# EDA

In [1]:
import pandas as pd
import sqlite3 as sq

In [2]:
conn=sq.connect('inventory.db')

In [3]:
tables=pd.read_sql_query("select name from sqlite_master where type='table'",conn)
tables

                       name
0     2017PurchasePricesDec
1       BegInvFINAL12312016
2       EndInvFINAL12312016
3  InvoicePurchases12312016
4    PurchasesFINAL12312016
5        SalesFINAL12312016

In [4]:
# pd.read_sql("select * from 'BegInvFINAL12312016'",conn)
for table in tables['name']:
    print('-'*50,f'{table}','-'*50)
    print(f'count of records:',pd.read_sql(f"select count(*) as count  from '{table}' ",conn)['count'].values[0])
    display(pd.read_sql(f" select *  from '{table}' limit 5 ",conn))

-------------------------------------------------- 2017PurchasePricesDec --------------------------------------------------
count of records: 12261

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,58,Gekkeikan Black & Gold Sake,12.99,750mL,750,1,9.28,8320,SHAW ROSS INT L IMP LTD
1,62,Herradura Silver Tequila,36.99,750mL,750,1,28.67,1128,BROWN-FORMAN CORP
2,63,Herradura Reposado Tequila,38.99,750mL,750,1,30.46,1128,BROWN-FORMAN CORP
3,72,No. 3 London Dry Gin,34.99,750mL,750,1,26.11,9165,ULTRA BEVERAGE COMPANY LLP
4,75,Three Olives Tomato Vodka,14.99,750mL,750,1,10.94,7245,PROXIMO SPIRITS INC.

-------------------------------------------------- BegInvFINAL12312016 --------------------------------------------------
count of records: 206529

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,startDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,8,12.99,2016-01-01
1,1_HARDERSFIELD_60,1,HARDERSFIELD,60,Canadian Club 1858 VAP,750mL,7,10.99,2016-01-01
2,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,6,36.99,2016-01-01
3,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,3,38.99,2016-01-01
4,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,6,34.99,2016-01-01

-------------------------------------------------- EndInvFINAL12312016 --------------------------------------------------
count of records: 224489

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,endDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,11,12.99,2016-12-31
1,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,7,36.99,2016-12-31
2,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,7,38.99,2016-12-31
3,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,4,34.99,2016-12-31
4,1_HARDERSFIELD_75,1,HARDERSFIELD,75,Three Olives Tomato Vodka,750mL,7,14.99,2016-12-31

-------------------------------------------------- InvoicePurchases12312016 --------------------------------------------------
count of records: 5543

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,105,ALTAMAR BRANDS LLC,2016-01-04,8124,2015-12-21,2016-02-16,6,214.26,3.47,None
1,4466,AMERICAN VINTAGE BEVERAGE,2016-01-07,8137,2015-12-22,2016-02-21,15,140.55,8.57,None
2,388,ATLANTIC IMPORTING COMPANY,2016-01-09,8169,2015-12-24,2016-02-16,5,106.60,4.61,None
3,480,BACARDI USA INC,2016-01-12,8106,2015-12-20,2016-02-05,10100,137483.78,2935.20,None
4,516,BANFI PRODUCTS CORP,2016-01-07,8170,2015-12-24,2016-02-12,1935,15527.25,429.20,None

-------------------------------------------------- PurchasesFINAL12312016 --------------------------------------------------
count of records: 2372474

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,69_MOUNTMEND_8412,69,8412,Tequila Ocho Plata Fresno,750mL,105,ALTAMAR BRANDS LLC,8124,2015-12-21,2016-01-02,2016-01-04,2016-02-16,35.71,6,214.26,1
1,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2015-12-22,2016-01-01,2016-01-07,2016-02-21,9.35,4,37.40,1
2,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2015-12-22,2016-01-02,2016-01-07,2016-02-21,9.41,5,47.05,1
3,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2015-12-22,2016-01-01,2016-01-07,2016-02-21,9.35,6,56.10,1
4,76_DONCASTER_2034,76,2034,Glendalough Double Barrel,750mL,388,ATLANTIC IMPORTING COMPANY,8169,2015-12-24,2016-01-02,2016-01-09,2016-02-16,21.32,5,106.60,1

-------------------------------------------------- SalesFINAL12312016 --------------------------------------------------
count of records: 1048575

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,1/1/2016,750,1,0.79,12546,JIM BEAM BRANDS COMPANY
1,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,2,32.98,16.49,1/2/2016,750,1,1.57,12546,JIM BEAM BRANDS COMPANY
2,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,1/3/2016,750,1,0.79,12546,JIM BEAM BRANDS COMPANY
3,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,14.49,14.49,1/8/2016,750,1,0.79,12546,JIM BEAM BRANDS COMPANY
4,1_HARDERSFIELD_1005,1,1005,Maker's Mark Combo Pack,375mL 2 Pk,2,69.98,34.99,1/9/2016,375,1,0.79,12546,JIM BEAM BRANDS COMPANY

In [5]:
purchase=pd.read_sql_query('select * from purchasesFINAL12312016 where VendorNumber = 4466',conn)
purchase

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2015-12-22,2016-01-01,2016-01-07,2016-02-21,9.35,4,37.40,1
1,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2015-12-22,2016-01-02,2016-01-07,2016-02-21,9.41,5,47.05,1
2,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2015-12-22,2016-01-01,2016-01-07,2016-02-21,9.35,6,56.10,1
3,38_GOULCREST_5215,38,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8207,2015-12-27,2016-01-07,2016-01-19,2016-02-26,9.41,6,56.46,1
4,59_CLAETHORPES_5215,59,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8207,2015-12-27,2016-01-05,2016-01-19,2016-02-26,9.41,6,56.46,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2187,81_PEMBROKE_5215,81,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2016-12-20,2016-12-29,2017-01-04,2017-02-10,9.41,6,56.46,1
2188,62_KILMARNOCK_5255,62,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2016-12-20,2016-12-28,2017-01-04,2017-02-10,9.35,5,46.75,1
2189,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2016-12-20,2016-12-28,2017-01-04,2017-02-10,9.41,5,47.05,1
2190,6_GOULCREST_5215,6,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2016-12-20,2016-12-31,2017-01-04,2017-02-10,9.41,6,56.46,1
2191,35_HALIVAARA_5255,35,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2016-12-20,2016-12-27,2017-01-04,2017-02-10,9.35,5,46.75,1

In [6]:
tables=pd.read_sql_query("select name from sqlite_master where type='table'",conn)
tables

                       name
0     2017PurchasePricesDec
1       BegInvFINAL12312016
2       EndInvFINAL12312016
3  InvoicePurchases12312016
4    PurchasesFINAL12312016
5        SalesFINAL12312016

In [7]:
purchase_prices=pd.read_sql_query('select * from "2017PurchasePricesDec" where VendorNumber = 4466',conn)
purchase_prices

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,5215,TGI Fridays Long Island Iced,12.99,1750mL,1750,1,9.41,4466,AMERICAN VINTAGE BEVERAGE
1,5255,TGI Fridays Ultimte Mudslide,12.99,1750mL,1750,1,9.35,4466,AMERICAN VINTAGE BEVERAGE
2,3140,TGI Fridays Orange Dream,14.99,1750mL,1750,1,11.19,4466,AMERICAN VINTAGE BEVERAGE

In [8]:
Vendor_Invoice=pd.read_sql_query('select * from "InvoicePurchases12312016" where VendorNumber = 4466',conn)
Vendor_Invoice

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,4466,AMERICAN VINTAGE BEVERAGE,2016-01-07,8137,2015-12-22,2016-02-21,15,140.55,8.57,None
1,4466,AMERICAN VINTAGE BEVERAGE,2016-01-19,8207,2015-12-27,2016-02-26,335,3142.33,16.97,None
2,4466,AMERICAN VINTAGE BEVERAGE,2016-01-18,8307,2016-01-03,2016-02-18,41,383.35,1.99,None
3,4466,AMERICAN VINTAGE BEVERAGE,2016-01-27,8469,2016-01-14,2016-03-11,72,673.20,3.30,None
4,4466,AMERICAN VINTAGE BEVERAGE,2016-02-04,8532,2016-01-19,2016-03-15,79,740.21,3.48,None
5,4466,AMERICAN VINTAGE BEVERAGE,2016-02-09,8604,2016-01-24,2016-03-15,347,3261.37,17.61,None
6,4466,AMERICAN VINTAGE BEVERAGE,2016-02-17,8793,2016-02-05,2016-04-02,72,675.36,3.17,None
7,4466,AMERICAN VINTAGE BEVERAGE,2016-03-01,8892,2016-02-12,2016-03-28,117,1096.05,5.15,None
8,4466,AMERICAN VINTAGE BEVERAGE,2016-03-07,8995,2016-02-19,2016-04-02,129,1209.27,5.44,None
9,4466,AMERICAN VINTAGE BEVERAGE,2016-03-12,9033,2016-02-22,2016-04-16,147,1377.87,6.61,None
10,4466,AMERICAN VINTAGE BEVERAGE,2016-03-16,9180,2016-03-03,2016-04-19,211,1979.33,9.50,None
11,4466,AMERICAN VINTAGE BEVERAGE,2016-03-23,9244,2016-03-08,2016-04-21,161,1510.69,6.95,None
12,4466,AMERICAN VINTAGE BEVERAGE,2016-03-31,9371,2016-03-17,2016-05-13,176,1649.20,8.91,None
13,4466,AMERICAN VINTAGE BEVERAGE,2016-04-09,9491,2016-03-24,2016-05-08,215,2016.43,10.08,None
14,4466,AMERICAN VINTAGE BEVERAGE,2016-04-17,9583,2016-03-31,2016-05-12,110,1035.10,5.69,None
15,4466,AMERICAN VINTAGE BEVERAGE,2016-04-20,9639,2016-04-04,2016-06-04,515,5323.01,25.02,None
16,4466,AMERICAN VINTAGE BEVERAGE,2016-04-29,9800,2016-04-15,2016-06-07,275,2775.01,13.60,None
17,4466,AMERICAN VINTAGE BEVERAGE,2016-05-09,9886,2016-04-21,2016-06-12,312,3050.86,13.73,None
18,4466,AMERICAN VINTAGE BEVERAGE,2016-05-14,9999,2016-04-29,2016-06-26,310,3117.82,14.97,None
19,4466,AMERICAN VINTAGE BEVERAGE,2016-05-16,10095,2016-05-06,2016-06-27,215,2123.01,11.46,None
20,4466,AMERICAN VINTAGE BEVERAGE,2016-05-28,10169,2016-05-11,2016-07-04,327,3298.55,15.83,None
21,4466,AMERICAN VINTAGE BEVERAGE,2016-06-04,10257,2016-05-17,2016-07-08,376,3708.18,20.39,None
22,4466,AMERICAN VINTAGE BEVERAGE,2016-06-12,10346,2016-05-23,2016-07-20,640,6458.38,29.71,None
23,4466,AMERICAN VINTAGE BEVERAGE,2016-06-17,10445,2016-05-30,2016-07-19,288,2937.56,15.86,None
24,4466,AMERICAN VINTAGE BEVERAGE,2016-06-22,10600,2016-06-09,2016-08-01,308,3213.28,17.03,None
25,4466,AMERICAN VINTAGE BEVERAGE,2016-06-29,10695,2016-06-16,2016-08-12,143,1585.75,8.09,None
26,4466,AMERICAN VINTAGE BEVERAGE,2016-07-09,10777,2016-06-22,2016-08-15,18,179.88,0.99,None
27,4466,AMERICAN VINTAGE BEVERAGE,2016-07-08,10836,2016-06-25,2016-08-14,8,85.96,0.43,None
28,4466,AMERICAN VINTAGE BEVERAGE,2016-07-11,10969,2016-06-29,2016-08-18,94,993.12,5.06,None
29,4466,AMERICAN VINTAGE BEVERAGE,2016-07-19,11085,2016-07-06,2016-09-04,601,5883.09,31.18,None
30,4466,AMERICAN VINTAGE BEVERAGE,2016-07-26,11187,2016-07-14,2016-08-26,1535,15406.69,77.03,None
31,4466,AMERICAN VINTAGE BEVERAGE,2016-08-03,11244,2016-07-18,2016-09-04,266,2888.22,15.31,None
32,4466,AMERICAN VINTAGE BEVERAGE,2016-08-11,11362,2016-07-26,2016-09-24,206,2171.64,11.08,None
33,4466,AMERICAN VINTAGE BEVERAGE,2016-08-18,11489,2016-08-04,2016-09-16,768,7292.98,37.92,None
34,4466,AMERICAN VINTAGE BEVERAGE,2016-08-24,11540,2016-08-08,2016-10-02,1207,12242.43,64.88,None
35,4466,AMERICAN VINTAGE BEVERAGE,2016-09-02,11716,2016-08-19,2016-09-29,433,4334.43,20.37,None
36,4466,AMERICAN VINTAGE BEVERAGE,2016-09-12,11771,2016-08-23,2016-10-11,370,3640.18,18.20,None
37,4466,AMERICAN VINTAGE BEVERAGE,2016-09-20,11901,2016-09-01,2016-10-30,358,3626.74,16.32,None
38,4466,AMERICAN VINTAGE BEVERAGE,2016-09-25,11993,2016-09-07,2016-10-23,233,2264.85,12.23,None
39,4466,AMERICAN VINTAGE BEVERAGE,2016-10-01,12125,2016-09-16,2016-11-07,284,2813.46,15.47,None
40,4466,AMERICAN VINTAGE BEVERAGE,2016-10-08,12235,2016-09-23,2016-11-20,258,2592.08,11.92,None
41,4466,AMERICAN VINTAGE BEVERAGE,2016-10-09,12253,2016-09-23,2016-11-14,1,11.19,0.05,None
42,4466,AMERICAN VINTAGE BEVERAGE,2016-10-12,12321,2016-09-26,2016-11-19,172,1685.98,7.59,None
43,4466,AMERICAN VINTAGE BEVERAGE,2016-10-20,12466,2016-10-05,2016-11-26,280,2798.60,14.55,None
44,4466,AMERICAN VINTAGE BEVERAGE,2016-10-27,12515,2016-10-09,2016-11-30,178,1763.28,8.64,None
45,4466,AMERICAN VINTAGE BEVERAGE,2016-11-07,12702,2016-10-21,2016-12-11,183,1812.77,8.70,None
46,4466,AMERICAN VINTAGE BEVERAGE,2016-11-12,12752,2016-10-25,2016-12-11,216,2156.16,10.57,None
47,4466,AMERICAN VINTAGE BEVERAGE,2016-11-20,12828,2016-10-30,2016-12-18,262,2597.36,12.99,None
48,4466,AMERICAN VINTAGE BEVERAGE,2016-11-27,12929,2016-11-06,2017-01-04,270,2622.32,12.85,None
49,4466,AMERICAN VINTAGE BEVERAGE,2016-11-28,13092,2016-11-16,2016-12-30,209,2036.17,11.20,None
50,4466,AMERICAN VINTAGE BEVERAGE,2016-12-06,13134,2016-11-20,2017-01-18,305,3018.89,15.70,None
51,4466,AMERICAN VINTAGE BEVERAGE,2016-12-16,13254,2016-11-28,2017-01-13,262,2530.36,11.39,None
52,4466,AMERICAN VINTAGE BEVERAGE,2016-12-26,13432,2016-12-09,2017-01-27,231,2263.43,11.32,None
53,4466,AMERICAN VINTAGE BEVERAGE,2016-12-30,13483,2016-12-13,2017-02-11,221,2178.27,11.33,None
54,4466,AMERICAN VINTAGE BEVERAGE,2017-01-09,13627,2016-12-22,2017-02-05,413,3985.03,19.53,None

In [9]:
# sales=pd.read_sql_query('select * from "SalesFINAL12312016" where VendorNumber = 4466',conn)
# sales

sales=pd.read_sql_query('select * from "SalesFINAL12312016" where VendorNo = 4466',conn)
sales

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,1/9/2016,1750,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
1,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,1/12/2016,1750,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
2,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,1/15/2016,1750,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
3,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,1/21/2016,1750,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
4,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,1/23/2016,1750,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
426,15_WANBORNE_5215,15,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2/23/2016,1750,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
427,15_WANBORNE_5255,15,5255,TGI Fridays Ultimte Mudslide,1.75L,1,12.99,12.99,2/3/2016,1750,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
428,15_WANBORNE_5255,15,5255,TGI Fridays Ultimte Mudslide,1.75L,1,12.99,12.99,2/23/2016,1750,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
429,15_WANBORNE_5255,15,5255,TGI Fridays Ultimte Mudslide,1.75L,1,12.99,12.99,2/24/2016,1750,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
430,15_WANBORNE_5255,15,5255,TGI Fridays Ultimte Mudslide,1.75L,2,25.98,12.99,2/27/2016,1750,1,3.67,4466,AMERICAN VINTAGE BEVERAGE

In [10]:
purchase.groupby(['Brand','PurchasePrice'])[['Quantity','Dollars']].sum()

                     Quantity   Dollars
Brand PurchasePrice
3140  11.19              4640  51921.60
5215  9.41               4923  46325.43
5255  9.35               6215  58110.25

In [11]:
Vendor_Invoice['PONumber'].nunique() # number of unique data

55

In [12]:
Vendor_Invoice.columns

Index(['VendorNumber', 'VendorName', 'InvoiceDate', 'PONumber', 'PODate',
       'PayDate', 'Quantity', 'Dollars', 'Freight', 'Approval'],
      dtype='object')

In [13]:
Vendor_Invoice.shape

(55, 10)

In [14]:
sales.columns

Index(['InventoryId', 'Store', 'Brand', 'Description', 'Size', 'SalesQuantity',
       'SalesDollars', 'SalesPrice', 'SalesDate', 'Volume', 'Classification',
       'ExciseTax', 'VendorNo', 'VendorName'],
      dtype='object')

In [15]:
sales.groupby('Brand')[['SalesDollars','SalesPrice','SalesQuantity']].sum()

       SalesDollars  SalesPrice  SalesQuantity
Brand
5215        3897.00     2416.14            300
5255        4273.71     3182.55            329

In [16]:
fright_summery = pd.read_sql_query('''select VendorNumber, SUM(Freight) as Total_Fright 
from InvoicePurchases12312016
group by VendorNumber''', conn)

In [17]:
fright_summery

     VendorNumber  Total_Fright
0               2         27.08
1              54          0.48
2              60        367.52
3             105         62.39
4             200          6.19
..            ...           ...
121         98450        856.02
122         99166        130.09
123        172662        178.34
124        173357        202.50
125        201359          0.09

[126 rows x 2 columns]

In [18]:
pd.read_sql_query('''select
    p.VendorNumber,
    p.VendorName,
    p.Brand,
    p.PurchasePrice,
    pp.Volume,
    pp.Price,
    SUM(p.Quantity) as TotalPurchaseQuantity,
    SUM(p.Dollars) as TotalPurchaseDoller
    from "PurchasesFINAL12312016" p
    JOIN "2017PurchasePricesDec" pp
    ON p.Brand=pp.Brand
    where p.PurchasePrice > 0
    Group by p.VendorNumber,p.VendorName ,p.Brand
    order by TotalPurchaseDoller
''', conn)

,VendorNumber,VendorName,Brand,PurchasePrice,Volume,Price,TotalPurchaseQuantity,TotalPurchaseDoller
0,7245,PROXIMO SPIRITS INC.,3065,0.71,50,0.99,1,0.71
1,3960,DIAGEO NORTH AMERICA INC,6127,1.47,200,1.99,1,1.47
2,3924,HEAVEN HILL DISTILLERIES,9123,0.74,50,0.99,2,1.48
3,8004,SAZERAC CO INC,5683,0.39,50,0.49,6,2.34
4,9815,WINE GROUP INC,8527,1.32,750,4.99,2,2.64
...,...,...,...,...,...,...,...,...
10687,3960,DIAGEO NORTH AMERICA INC,3545,21.89,1750,29.99,138109,3023206.01
10688,3960,DIAGEO NORTH AMERICA INC,4261,16.17,1750,22.99,201682,3261197.94
10689,17035,PERNOD RICARD USA,8068,18.24,1750,24.99,187407,3418303.68
10690,4425,MARTIGNETTI COMPANIES,3405,23.19,1750,28.99,164038,3804041.22
10691,1128,BROWN-FORMAN CORP,1233,26.27,1750,36.99,145080,3811251.60

In [19]:
sales.columns

Index(['InventoryId', 'Store', 'Brand', 'Description', 'Size', 'SalesQuantity',
       'SalesDollars', 'SalesPrice', 'SalesDate', 'Volume', 'Classification',
       'ExciseTax', 'VendorNo', 'VendorName'],
      dtype='object')

In [20]:
 pd.read_sql_query('''select
     VendorNo,
     Brand,
     sum(SalesDollars) as TotalSalesDoller,
     sum(SalesPrice) as TotalSalesPrice,
     sum(SalesQuantity) as TotalSalesQuantity,
     sum(ExciseTax) as TotalExciseTax
     from "SalesFINAL12312016"
     group by VendorNo , Brand
 ''', conn)

,VendorNo,Brand,TotalSalesDoller,TotalSalesPrice,TotalSalesQuantity,TotalExciseTax
0,2,90085,73.98,36.99,2,0.22
1,105,8412,749.85,699.86,15,11.84
2,105,8419,41.94,41.94,6,0.60
3,287,24921,46.47,46.47,3,0.33
4,287,24922,77.45,77.45,5,0.55
...,...,...,...,...,...,...
7653,98450,6877,170.91,170.91,9,7.11
7654,98450,7890,839.72,599.80,28,22.06
7655,98450,8543,1447.27,1007.49,73,57.54
7656,172662,4215,155.94,25.99,6,4.72
7657,173357,3909,1074.57,799.68,43,33.88

In [21]:
Vendor_sales_summery = pd.read_sql_query(
    '''
    SELECT
        p.VendorNumber,
        p.VendorName,
        p.Brand,
        p.PurchasePrice,
        pp.Volume,
        pp.Price,
        SUM(p.Quantity) AS TotalPurchaseQuantity,
        SUM(p.Dollars) AS TotalPurchaseDoller,
        s.TotalSalesDoller,
        s.TotalSalesPrice,
        s.TotalSalesQuantity,
        s.TotalExciseTax,
        f.Total_Fright
    FROM "PurchasesFINAL12312016" p
    JOIN "2017PurchasePricesDec" pp
        ON p.Brand = pp.Brand
    LEFT JOIN (
        SELECT
            VendorNo AS VendorNumber,
            Brand,
            SUM(SalesDollars) AS TotalSalesDoller,
            SUM(SalesPrice) AS TotalSalesPrice,
            SUM(SalesQuantity) AS TotalSalesQuantity,
            SUM(ExciseTax) AS TotalExciseTax
        FROM "SalesFINAL12312016"
        GROUP BY VendorNo, Brand
    ) s
        ON p.VendorNumber = s.VendorNumber
       AND p.Brand = s.Brand
    LEFT JOIN (
        SELECT
            VendorNumber,
            SUM(Freight) AS Total_Fright
        FROM InvoicePurchases12312016
        GROUP BY VendorNumber
    ) f
        ON p.VendorNumber = f.VendorNumber
    WHERE p.PurchasePrice > 0
    GROUP BY
        p.VendorNumber,
        p.VendorName,
        p.Brand
    ORDER BY TotalPurchaseDoller DESC
    ''', conn
)

#this query generate a vendor-wise sales and Purchase Summery, which is valuable for performance optimization

In [22]:
Vendor_sales_summery.dtypes

VendorNumber               int64
VendorName                object
Brand                      int64
PurchasePrice            float64
Volume                    object
Price                    float64
TotalPurchaseQuantity      int64
TotalPurchaseDoller      float64
TotalSalesDoller         float64
TotalSalesPrice          float64
TotalSalesQuantity       float64
TotalExciseTax           float64
Total_Fright             float64
dtype: object

In [23]:
Vendor_sales_summery['Volume'].head(5)

0    1750
1    1750
2    1750
3    1750
4    1750
Name: Volume, dtype: object

In [24]:
Vendor_sales_summery.isnull().sum()

VendorNumber                0
VendorName                  0
Brand                       0
PurchasePrice               0
Volume                      0
Price                       0
TotalPurchaseQuantity       0
TotalPurchaseDoller         0
TotalSalesDoller         3548
TotalSalesPrice          3548
TotalSalesQuantity       3548
TotalExciseTax           3548
Total_Fright                0
dtype: int64

In [34]:
Vendor_sales_summery['VendorName'].unique()

array(['BROWN-FORMAN CORP', 'MARTIGNETTI COMPANIES', 'PERNOD RICARD USA',
       'DIAGEO NORTH AMERICA INC', 'BACARDI USA INC',
       'JIM BEAM BRANDS COMPANY', 'MAJESTIC FINE WINES',
       'ULTRA BEVERAGE COMPANY LLP', 'STOLI GROUP,(USA) LLC',
       'PROXIMO SPIRITS INC.', 'MOET HENNESSY USA INC', 'CAMPARI AMERICA',
       'SAZERAC CO INC', 'CONSTELLATION BRANDS INC', 'M S WALKER INC',
       'SAZERAC NORTH AMERICA INC.', 'PALM BAY INTERNATIONAL INC',
       'REMY COINTREAU USA INC', 'SIDNEY FRANK IMPORTING CO',
       'E & J GALLO WINERY', 'WILLIAM GRANT & SONS INC',
       'HEAVEN HILL DISTILLERIES', 'DISARONNO INTERNATIONAL LLC',
       'EDRINGTON AMERICAS', 'CASTLE BRANDS CORP.',
       'SOUTHERN WINE & SPIRITS NE', 'STE MICHELLE WINE ESTATES',
       'TRINCHERO FAMILY ESTATES', 'MHW LTD', 'WINE GROUP INC',
       'PERFECTA WINES', 'LUXCO INC', 'TREASURY WINE ESTATES',
       'DIAGEO CHATEAU ESTATE WINES', 'SHAW ROSS INT L IMP LTD',
       'PINE STATE TRADING CO', 'PHILLIPS PRODUCTS CO.',
       'CALEDONIA SPIRITS INC', 'STATE WINE & SPIRITS',
       'KOBRAND CORPORATION', 'BANFI PRODUCTS CORP',
       'VINEYARD BRANDS INC', 'DELICATO VINEYARDS INC',
       'FABRIZIA SPIRITS LLC', 'DUGGANS DISTILLED PRODUCTS',
       'Serralles Usa LLC', 'SEA HAGG DISTILLERY LLC',
       'OLE SMOKY DISTILLERY LLC', 'VRANKEN AMERICA', 'KLIN SPIRITS LLC',
       'LAIRD & CO', 'ADAMBA IMPORTS INTL INC',
       'LATITUDE BEVERAGE COMPANY', 'FREDERICK WILDMAN & SONS',
       'MCCORMICK DISTILLING CO', 'CHARLES JACQUIN ET CIE INC',
       'WESTERN SPIRITS BEVERAGE CO', 'MARSALLE COMPANY',
       'AMERICAN VINTAGE BEVERAGE', 'MANGO BOTTLING INC',
       'SWEET BABY VINEYARD', 'NICHE W & S', 'LABELLE VYDS AND WINERY',
       'FLAG HILL WINERY & VINEYARD', 'SMOKY QUARTZ DISTILLERY LLC',
       'PREMIUM PORT WINES, INC.', 'Russian Standard Vodka',
       'Dunn Wine Brokers', 'WEIN BAUER INC', 'BULLY BOY DISTILLERS',
       'ATLANTIC IMPORTING COMPANY', 'PREMIER DISTRIBUTORS',
       'VINILANDIA USA', 'PARK STREET IMPORTS LLC', 'TAKARA SAKE USA INC',
       'SEA BREEZE CELLARS LLC', 'STARK BREWING COMPANY', 'TY KU LLC',
       'PSP WINES', 'TAMWORTH DISTILLING', 'ZORVINO VINEYARDS',
       'SOUTHERN GLAZERS W&S OF NE', 'HOOD RIVER DISTILLERS, Inc.',
       'CRUSH WINES', 'POVERTY LANE ORCHARDS', 'DJINN SPIRITS LLC',
       'MOONLIGHT MEADERY', 'TALL SHIP DISTILLERY LLC',
       'FORTUNE WINE BROKERS LLC', 'BLACK COVE BEVERAGES', 'VINEXTRA INC',
       'SURVILLE ENTERPRISES CORP', 'JEWELL TOWNE VINEYARDS',
       'SWEETWATER FARM', 'ALTAMAR BRANDS LLC', 'CANDIA VINEYARDS',
       'INCREDIBREW INC', 'ALISA CARR BEVERAGES',
       'STELLAR IMPORTING CO LLC', 'FULCHINO VINEYARD INC',
       'IRA GOLDMAN AND WILLIAMS, LLP', 'Circa Wines',
       'VINEDREA WINES LLC', 'BLACK PRINCE DISTILLERY INC',
       'VINEYARD BRANDS LLC', 'THE IMPORTED GRAPE LLC',
       'WALPOLE MTN VIEW WINERY', 'GILMANTON WINERY & VINEYARD',
       'HAUNTING WHISPER VYDS', 'STAR INDUSTRIES INC.',
       'LOYAL DOG WINERY', 'R.P.IMPORTS INC', 'THE PIERPONT GROUP LLC',
       'APPOLO VINEYARDS LLC', 'BLACK ROCK SPIRITS LLC',
       'CENTEUR IMPORTS LLC', 'HIGHLAND WINE MERCHANTS LLC',
       'AMERICAN SPIRITS EXCHANGE', 'UNCORKED', 'BRONCO WINE COMPANY',
       'MILTONS DISTRIBUTING CO', 'TRUETT HURST', 'LAUREATE IMPORTS CO',
       'FANTASY FINE WINES CORP', 'AAPER ALCOHOL & CHEMICAL CO',
       'SILVER MOUNTAIN CIDERS', 'CAPSTONE INTERNATIONAL',
       'FLAVOR ESSENCE INC'], dtype=object)

In [26]:
Vendor_sales_summery.columns

Index(['VendorNumber', 'VendorName', 'Brand', 'PurchasePrice', 'Volume',
       'Price', 'TotalPurchaseQuantity', 'TotalPurchaseDoller',
       'TotalSalesDoller', 'TotalSalesPrice', 'TotalSalesQuantity',
       'TotalExciseTax', 'Total_Fright'],
      dtype='object')

In [27]:
Vendor_sales_summery['VendorNumber'].head(8).sum()

51983

In [28]:
Vendor_sales_summery['Volume']=Vendor_sales_summery['Volume'].astype('float64')

In [29]:
Vendor_sales_summery.dtypes

VendorNumber               int64
VendorName                object
Brand                      int64
PurchasePrice            float64
Volume                   float64
Price                    float64
TotalPurchaseQuantity      int64
TotalPurchaseDoller      float64
TotalSalesDoller         float64
TotalSalesPrice          float64
TotalSalesQuantity       float64
TotalExciseTax           float64
Total_Fright             float64
dtype: object

In [30]:
Vendor_sales_summery.fillna(0,inplace=True)

In [32]:
Vendor_sales_summery['VendorName']=Vendor_sales_summery['VendorName'].str.strip()

In [33]:
Vendor_sales_summery['VendorName']

0               BROWN-FORMAN CORP
1           MARTIGNETTI COMPANIES
2               PERNOD RICARD USA
3        DIAGEO NORTH AMERICA INC
4        DIAGEO NORTH AMERICA INC
                   ...
10687              WINE GROUP INC
10688              SAZERAC CO INC
10689    HEAVEN HILL DISTILLERIES
10690    DIAGEO NORTH AMERICA INC
10691        PROXIMO SPIRITS INC.
Name: VendorName, Length: 10692, dtype: object

In [58]:
Vendor_sales_summery.columns

Index(['VendorNumber', 'VendorName', 'Brand', 'PurchasePrice', 'Volume',
       'Price', 'TotalPurchaseQuantity', 'TotalPurchaseDoller',
       'TotalSalesDoller', 'TotalSalesPrice', 'TotalSalesQuantity',
       'TotalExciseTax', 'Total_Fright'],
      dtype='object')

In [70]:
Vendor_sales_summery['GrossProfit'] = Vendor_sales_summery['TotalSalesDoller'] - Vendor_sales_summery['TotalPurchaseDoller']

In [67]:
Vendor_sales_summery['ProfitMargin']=(Vendor_sales_summery['GrossProfit'] / Vendor_sales_summery['TotalSalesDoller'])*100

In [71]:
Vendor_sales_summery['StockTurnover'] = Vendor_sales_summery['TotalSalesQuantity']/Vendor_sales_summery['TotalPurchaseQuantity']

In [72]:
Vendor_sales_summery['SalestopurchaseRatio'] = Vendor_sales_summery['TotalSalesDoller']/Vendor_sales_summery['TotalPurchaseDoller']

In [73]:
cursor=conn.cursor()

In [74]:
cursor.execute('''CREATE TABLE Vendor_Sales_Summary(
    VendorNumber INT,
    VendorName VARCHAR(100),
    Brand INT,
    Description Varchar(100),
    PurchasePrice Decimal(10,2),
    ActualPrice Decimal(10,2),
    Volume,
    TotalPurchaseQuantity INT,
    TotalPurchaseDoller Decimal(15,2),
    TotalSalesQuantity INT,
    TotalSalesDoller Decimal(15,2),
    TotalSalesPrice Decimal(15,2),
    TotalExciseTax Decimal(15,2),
    FreightCost Decimal(15,2),
    GrossProfit Decimal(15,2),
    ProfitMargin Decimal(15,2),
    StockTurnover Decimal(15,2),
    SalesToPurchaseRation Decimal(15,2),
    Primary KEY (VendorNumber , Brand)
);
''')

In [78]:
pd.read_sql_query('select * from Vendor_Sales_Summary',conn)

Empty DataFrame
Columns: [VendorNumber, VendorName, Brand, Description, PurchasePrice, ActualPrice, Volume, TotalPurchaseQuantity, TotalPurchaseDoller, TotalSalesQuantity, TotalSalesDoller, TotalSalesPrice, TotalExciseTax, FreightCost, GrossProfit, ProfitMargin, StockTurnover, SalesToPurchaseRation]
Index: []

In [80]:
Vendor_sales_summery.to_sql('Vendor_Sales_Summary',conn, if_exists = 'replace', index=False)

10692

In [82]:
pd.read_sql_query('select * from Vendor_Sales_summary',conn)

,VendorNumber,VendorName,Brand,PurchasePrice,Volume,Price,TotalPurchaseQuantity,TotalPurchaseDoller,TotalSalesDoller,TotalSalesPrice,TotalSalesQuantity,TotalExciseTax,Total_Fright,GrossProfit,ProfitMargin,SalestopurchaseRatio,StockTurnover
0,1128,BROWN-FORMAN CORP,1233,26.27,1750.0,36.99,145080,3811251.60,344712.22,64889.97,9578.0,17598.14,68601.68,-3466539.38,-1005.632867,0.090446,0.066019
1,4425,MARTIGNETTI COMPANIES,3405,23.19,1750.0,28.99,164038,3804041.22,275162.97,52289.50,9203.0,16909.12,144929.24,-3528878.25,-1282.468440,0.072334,0.056103
2,17035,PERNOD RICARD USA,8068,18.24,1750.0,24.99,187407,3418303.68,288135.11,48202.30,11189.0,20557.97,123780.22,-3130168.57,-1086.354443,0.084292,0.059704
3,3960,DIAGEO NORTH AMERICA INC,4261,16.17,1750.0,22.99,201682,3261197.94,444810.74,43304.31,20226.0,37163.76,257032.07,-2816387.20,-633.165287,0.136395,0.100287
4,3960,DIAGEO NORTH AMERICA INC,3545,21.89,1750.0,29.99,138109,3023206.01,357759.17,52774.51,11883.0,21833.58,257032.07,-2665446.84,-745.039419,0.118338,0.086041
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10687,9815,WINE GROUP INC,8527,1.32,750.0,4.99,2,2.64,5.97,5.97,3.0,0.33,27100.41,3.33,55.778894,2.261364,1.500000
10688,8004,SAZERAC CO INC,5683,0.39,50.0,0.49,6,2.34,62.72,0.98,128.0,6.72,50293.62,60.38,96.269133,26.803419,21.333333
10689,3924,HEAVEN HILL DISTILLERIES,9123,0.74,50.0,0.99,2,1.48,0.00,0.00,0.0,0.00,14069.87,-1.48,-inf,0.000000,0.000000
10690,3960,DIAGEO NORTH AMERICA INC,6127,1.47,200.0,1.99,1,1.47,11.94,7.96,6.0,1.26,257032.07,10.47,87.688442,8.122449,6.000000
10691,7245,PROXIMO SPIRITS INC.,3065,0.71,50.0,0.99,1,0.71,80.19,29.70,81.0,4.21,38994.78,79.48,99.114603,112.943662,81.000000